name: "Publish tags to FlakeHub"
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Existing repo tag to publish"
        required: true

permissions:
  id-token: "write"
  contents: "read"

jobs:
  flakehub-publish:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v6"
        with:
          ref: "${{ inputs.tag != '' && format('refs/tags/{0}', inputs.tag) || github.ref }}"
          persist-credentials: false
      - uses: "DeterminateSystems/determinate-nix-action@v3"
      - uses: "DeterminateSystems/flakehub-push@main"
        with:
          name: "ErikBPF/hermes-flake"
          rolling: false
          tag: "${{ inputs.tag != '' && inputs.tag || github.ref_name }}"
          visibility: "public"
          include-output-paths: true
